dist: xenial
language: python
python: "3.6"

sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get --purge remove ghostscript
  - sudo apt-get install libgs9=9.10~dfsg-0ubuntu10
  - sudo apt-get install -f ghostscript=9.10~dfsg-0ubuntu10
  - sudo apt install imagemagick

script:
  - ls -la tests/scanned/
  - which gs
  - which convert
  - python tests/tests.py
  - convert ./tests/scanned/two_scanned_sheets.pdf converted.png
  - ls -la
