dist: xenial
language: python
python: "3.6"

sudo: required

install:
  - sudo apt install autoconf imagemagick
  - sudo apt purge ghostscript

script:
  - python tests/tests.py
  - ls -la tests/scanned/
  - which gs
  - which convert
  - git clone --depth 1 git://git.ghostscript.com/ghostpdl.git
  - cd ghostpdl/
  - ./autogen.sh
  - ./configure
  - make && sudo make install
  - gs --version
  - convert ./tests/scanned/two_scanned_sheets.pdf converted.png
  - ls -la
