language: python
python:
  - "3.6"

sudo: required

install:
  - sudo apt install imagemagick

script:
  - ls -la tests/scanned/
  - which convert
  - python tests/tests.py
  - convert -density 100 tests/scanned/two_scanned_sheets.pdf converted.png
  - ls -la
