language: python
python: "3.6"

dist: xenial
sudo: required

before_script:
  - sudo apt update      
  - sudo apt install -y autoconf imagemagick mercurial unzip
  # configure imagemagick policies
  - sudo sed -i -e 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
  # clone and install ghostscript
  - git clone --depth 1 git://git.ghostscript.com/ghostpdl.git
  - cd ghostpdl/ && bash autogen.sh && bash configure && make && sudo make install
  - cd ../
  # clone and build the formscanner executables
  - wget https://sourceforge.net/code-snapshots/hg/u/u/u/agkortzis/formscanner/u-agkortzis-formscanner-09da5acba6e0328f6d9ef26b62751b33e77875d2.zip
  - unzip u-agkortzis-formscanner-09da5acba6e0328f6d9ef26b62751b33e77875d2.zip
  - ls -la
  - mv u-agkortzis-formscanner-09da5acba6e0328f6d9ef26b62751b33e77875d2 formscanner
  - cd formscanner
  - mvn clean package -Dgpg.skip -Dmaven.javadoc.skip=true
  - cd ..
  - cp formscanner/formscanner-distribution/target/formscanner-1.1.2-bin/lib/* lib/
  - ls -la lib/
script:
  - python tests/tests.py
  - sudo convert -density 100 tests/scanned/two_scanned_sheets.pdf -resize 594x841 converted.png
  - python3 examQuestionnaireScanner.py tests/scanned/ tests/input_data/FormScanner_test_template.xtmpl tests/input_data/test_student_info.csv
  - cat final_grades.csv | sort | sed 's/<//g' >> outputFile.txt
  - cat tests/input_data/grades_final_expected.csv | sort | sed 's/>//g'>> expectedFile.txt
  - cat outputFile.txt
  - cat expectedFile.txt
  - diff -s outputFile.txt expectedFile.txt
