dist: xenial
language: python
python: "3.6"

sudo: required

install:
  - sudo apt install libgs9 gsfonts ghostscript imagemagick

script:
  - ls -la tests/scanned/
  - which gs
  - which convert
  - python tests/tests.py
  - convert ./tests/scanned/two_scanned_sheets.pdf converted.png
  - ls -la
