dist: xenial
language: python
python: "3.6"

sudo: required

install:
  - sudo apt install imagemagick

script:
  - ls -la tests/scanned/
  - which gs
  - which convert
  - python tests/tests.py
  - wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/ghostscript-9.26-linux-x86_64.tgz
  - tar xvzf ghostscript-9.26-linux-x86_64.tgz
  - cd ghostscript-9.26-linux-x86_64
  - ./configure
  - make && sudo make install
  - gs --version
  - convert ./tests/scanned/two_scanned_sheets.pdf converted.png
  - ls -la
