import subprocess
import os 
import shutil
import argparse
from colorama import Fore, Back, Style 

parser = argparse.ArgumentParser()

parser.add_argument("scanned_pdf_directory", 
    help="The directory path that contains the pdf files generated by scanning the grade sheets.")
parser.add_argument("formScanner_template_xml",
    help="The path for the FormScanner template xml file.")
parser.add_argument("students_info",
    help="The path for the csv file that contains the student ids.")
parser.add_argument("-f", "--output_form_scanner_csv",
    help="The path for the csv file produced by FormScanner. The default will be used if not set by the user.")
parser.add_argument("-s", "--skip_pdf_conversion", action='store_true',
    help="A flag for skipping the pdf-to-images conversion")
parser.add_argument("-j", "--form_scanner_path", 
    help="The file path of the formscanner-main-XXX.jar executable. The default will be used if not set by the user.")
parser.add_argument("-o", "--final_grades_output_csv_file_path",
    help="The parsed csv file. The default will be used if not set by the user.")
args = parser.parse_args()


def execute_FormScanner(formScanner_path, formScanner_template_path, imagesDirectory_path, outputCSV_path):
    print('''## Scanning images with FormScanner ##
        - Using template :: {}'''
        .format(formScanner_template_path), flush=True)
    subprocess.call(['java', '-jar', formScanner_path, formScanner_template_path, imagesDirectory_path, outputCSV_path])
    print("- Finished.\n", flush=True)

# TODO: mention https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453
def execute_PdfToPngConverter(pdfDirecoty_path, outputImagesDir_path):
    print('''## Converting scanned pdf to images ##
        - PDF directory :: {}
        - Output images directory :: {}'''
        .format(pdfDirecoty_path, outputImagesDir_path), flush=True)    

    pdf_file_list = os.listdir(pdfDirecoty_path)
    for pdf in pdf_file_list:
        if pdf.endswith(".pdf"):
            pdf_file_path = os.path.join(pdfDirecoty_path, pdf)
            scanned_image_path = os.path.join(outputImagesDir_path, pdf)
            print("\t- Converting pdf :: {}".format(pdf_file_path), flush=True)
            subprocess.call(['convert', pdf_file_path, "-threshold", "90%", (scanned_image_path+"_converted.png")])
        else:
            # print("--- skipping :: {}".format(pdf))
            pass
    print("- Finished.\n", flush=True)


def execute_CsvParser(inputCSV_path, outputCSV_path, students_csv):
    print('''## Parsing FormScanner csv ##
        - CSV location :: {}
        - Course info xsls :: {}
        - Output CSV location :: {}'''
        .format(inputCSV_path, outputCSV_path, students_csv), flush=True)
    subprocess.call(["python", 
                    "CSVparser.py", 
                    (inputCSV_path + ".csv"), 
                    outputCSV_path,
                    students_csv]
                    )
    print("- Finished.\n", flush=True)


# initialize path variables
if args.scanned_pdf_directory:
    scanned_pdf_directory_path = args.scanned_pdf_directory
else: 
    # TODO: write erro to LOG
    pass

scanned_images_directory_path = "tmp"

# set the output formScannerCSV path
if args.output_form_scanner_csv:
    output_form_scanner_csv_path = args.output_form_scanner_csv
else:
    output_form_scanner_csv_path = os.path.join("tmp","formScannerCSV")

# set the FormScanner executable file path
if args.form_scanner_path:
    formScannerJar_path = args.form_scanner_path
else:
    formScannerJar_path = os.path.join("lib","formscanner-main-1.1.3.jar")

# set the FromScanner xml template file path
if args.formScanner_template_xml:
    formScanner_template_xml_path = args.formScanner_template_xml
else:
    # TODO: write to log
    pass
# set the parsed output csv file path
if args.final_grades_output_csv_file_path:
    final_grades_output_csv_file_path = args.final_grades_output_csv_file
else:
    final_grades_output_csv_file_path = os.path.join("tmp", "final_grades.csv")

# set the exam sheets file path
if args.students_info:
    students_info = args.students_info
else:
    # TODO: write to log
    pass

if args.skip_pdf_conversion:
    print("Skipping pdf to png conversion.", flush=True)
else:
    execute_PdfToPngConverter(scanned_pdf_directory_path, scanned_images_directory_path)

execute_FormScanner(formScannerJar_path, formScanner_template_xml_path, scanned_images_directory_path, output_form_scanner_csv_path)
execute_CsvParser(output_form_scanner_csv_path, final_grades_output_csv_file_path, students_info)